# Generated by Django 6.0.2 on 2026-02-26 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applemodel',
            name='cpass',
        ),
        migrations.AlterField(
            model_name='applemodel',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='applemodel',
            name='fname',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='applemodel',
            name='lname',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='applemodel',
            name='password',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='applemodel',
            name='phone',
            field=models.CharField(max_length=15),
        ),
    ]
