# Generated by Django 6.0.2 on 2026-02-26 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_applemodel_cpass_alter_applemodel_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applemodel',
            name='cpass',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='applemodel',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='applemodel',
            name='fname',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='applemodel',
            name='lname',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='applemodel',
            name='password',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='applemodel',
            name='phone',
            field=models.CharField(max_length=10),
        ),
    ]
